[package]
name = "get-certificates-expiration"
version = "0.1.0"
edition = "2024"

[dependencies]
openssl = "0.10"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

